bitten:
  aliyun:
    oss:
      endPoint: oss-cn-chengdu.aliyuncs.com
      accessKeyId: LTAI5tQyo3sqU9xKNZF7rRjB
      accessKeySecret: O3WA3FoLeyndyowq4UVT9bXtneJo8j
      bucketName: mt-takeout-oss
  middleware-host: 47.109.43.173
spring:
  datasource:
    password: root